### ISSUE TITLE
method not found

### ISSUE THREAD

**Issue by maheshts** [yanisalfian/flutter-phone-direct-caller#20]
Unhandled Exception: MissingPluginException(No implementation found for method callNumber on channel flutter_phone_direct_caller)

**Comment by Pedro-001** [comment]
> Unhandled Exception: MissingPluginException(No implementation found for method callNumber on channel flutter_phone_direct_caller)

Hi, if you need help to put into your app, follow this method https://medium.flutterdevs.com/implementing-phone-calls-using-the-flutter-app-e350ea275c92
