### ISSUE TITLE
Some way to handle phone call end.

### ISSUE THREAD

**Issue by szekelygobe** [yanisalfian/flutter-phone-direct-caller#5]
Is there a way I can trigger some code when the call is terminated ?

**Comment by yanisalfian** [comment]
You can refer to my comment [on this issue](https://github.com/yanisalfian/flutter-phone-direct-caller/issues/1#issuecomment-617829079).

Put your code to handle call termination inside ```phonecallstate.setDisconnectedHandler```.

```[dart]
    phonecallstate.setDisconnectedHandler(() {
      print("disconnected");
      if(connectedTime != null) {
        disconnectedTime = DateTime.now();
        var diff = disconnectedTime.difference(connectedTime);
        print(diff.inSeconds);
        c.complete(diff.inSeconds);
      }
    });
```

**Comment by szekelygobe** [comment]
@yanisalfian Thank you !
