### ISSUE TITLE
Not working on iPhone

### ISSUE THREAD

**Issue by szekelygobe** [yanisalfian/flutter-phone-direct-caller#6]
The package is working on Android emulator, when tested on iPhone emulator the package is not working.
No error or other message appears, only the print() is displaying 'test' from callNumber() function.
I added the LSApplicationQueriesSchemes key to the Info.plist file, and restarted the application.
What did I miss ? 
Did you tested on iPhone ?

**Comment by yanisalfian** [comment]
@szekelygobe  I've tested on iPhone and it worked. 

FYI, you cannot simulate phone calling on iPhone simulator. Phone call, sms, push notifications are some features that cannot be simulated on iPhone simulator.

You need to use real device.

**Comment by szekelygobe** [comment]
@yanisalfian Sorry, I'm starting with app development, I use you'r package form my first app :)

**Comment by szekelygobe** [comment]
I uploaded the app to my iPhone and I get this when calling a number

![Screenshot 2021-02-23 at 21 23 46](https://user-images.githubusercontent.com/6815413/108896836-1185a600-761e-11eb-822b-2e528b17fcc9.png)

I'd like to call directly without needing to tap to start the call.
Probably I'm missing something, can you help me out here?

**Comment by yanisalfian** [comment]
@szekelygobe Sorry to say, this is the behaviour of iPhone and can't be changed. 

iOS won't let app to call phone without letting the user know to where he/she will call. In iOS, with this plugin at least you can restrict your user from editing the phone number. But you can't restrict them from seeing the number.

**Comment by szekelygobe** [comment]
I'm not trying to restrict my user to see the number, I'm trying to call the number without user interaction. 
Like when you use Siri for "Siri call my wife" and it calls without this interface popping up.
I'm building a baby monitor app and I need the phone to call a number when a given noise level is reached.
So calling without the baby needing to tap on the call button :)

**Comment by szekelygobe** [comment]
I found this while searching for an answer : 
https://developer.apple.com/library/archive/featuredarticles/iPhoneURLScheme_Reference/PhoneLinks/PhoneLinks.html
Looks like Apple won't let an app call a number without user interaction, for security reasons.
